module.exports = locations = [
  {
    name: 'Paddhari',
    place_id: 'ChIJi5yXGhbbWTkRccWQUSaMikI',
    address_components: ['Padadhari', 'Rajkot', 'Gujarat', 'India', '360110'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Paddhari',
    },
    description: 'Padadhari, Gujarat, India',
    longitude: 70.60087229999999,
    latitude: 22.4354368,
  },
  {
    name: 'Jamnagar',
    place_id: 'ChIJl0XANEkVVzkRynWbpIHdt-g',
    address_components: ['Jamnagar', 'Jamnagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Jamnagar, Gujarat',
      main_text: 'Jamnagar',
    },
    description: 'Jamnagar, Jamnagar, Gujarat',
    longitude: 70.05773,
    latitude: 22.4707019,
  },
  {
    name: 'Adalaj',
    place_id: 'ChIJRYCEHNspXDkRcLJj313RVHE',
    address_components: ['Adalaj', 'Gandhinagar', 'Gujarat', 'India', '382421'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Adalaj',
    },
    description: 'Adalaj, Gujarat, India',
    longitude: 72.58095,
    latitude: 23.1667043,
  },
  {
    name: 'Rajkot',
    place_id: 'ChIJD98cx4rJWTkRO62Tvs8V3XY',
    address_components: ['Rajkot', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Rajkot',
    },
    description: 'Rajkot, Rajkot, Gujarat',
    longitude: 70.80215989999999,
    latitude: 22.3038945,
  },
  {
    name: 'Bodeli',
    place_id: 'ChIJfW-SWZduYDkRs1V8ELU2syk',
    address_components: ['Bodeli', 'Vadodara', 'Gujarat', 'India', '391135'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bodeli',
    },
    description: 'Bodeli, Gujarat, India',
    longitude: 73.714899,
    latitude: 22.2732666,
  },
  {
    name: 'Padavala',
    place_id: 'ChIJGWpNa0JKWDkRcDwLz0jlZvE',
    address_components: ['Padavala', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Padavala',
    },
    description: 'Padavala, Rajkot, Gujarat',
    longitude: 70.8328063,
    latitude: 22.155242,
  },
  {
    name: 'Rajpipla',
    place_id: 'ChIJg-Rkoy0HYDkRvqqPlkq8GHw',
    address_components: ['Rajpipla', 'Narmada', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Narmada, Gujarat',
      main_text: 'Rajpipla',
    },
    description: 'Rajpipla, Narmada, Gujarat',
    longitude: 73.5030517,
    latitude: 21.8715143,
  },
  {
    name: 'Wankaner',
    place_id: 'ChIJpSnGGzGWWTkRNSFipDIqKi8',
    address_components: ['Wankaner', 'Rajkot', 'Gujarat', 'India', '363621'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Wankaner',
    },
    description: 'Wankaner, Gujarat, India',
    longitude: 70.9616056,
    latitude: 22.623634,
  },
  {
    name: 'Ahmedabad',
    place_id: 'ChIJSdRbuoqEXjkRFmVPYRHdzk8',
    address_components: ['Ahmedabad', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Ahmedabad',
    },
    description: 'Ahmedabad, Ahmedabad, Gujarat',
    longitude: 72.5713621,
    latitude: 23.022505,
  },
  {
    name: 'Shapar',
    place_id: 'ChIJa_6EZp81WDkRcjPOcESRkPU',
    address_components: ['Shapar', 'Rajkot', 'Gujarat', 'India', '360024'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Shapar',
    },
    description: 'Shapar, Gujarat, India',
    longitude: 70.7990772,
    latitude: 22.1572507,
  },
  {
    name: 'GANDHINAGAR',
    place_id: 'ChIJCWhtfJgrXDkRkQM-h6cGb_g',
    address_components: ['Gandhinagar', 'Gandhinagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Gandhinagar, Gujarat',
      main_text: 'Gandhinagar',
    },
    description: 'Gandhinagar, Gandhinagar, Gujarat',
    longitude: 72.63694149999999,
    latitude: 23.2156354,
  },
  {
    name: 'TARAGADIA',
    place_id: 'ChIJdzjGjW6nGToRel-w71-KYe8',
    address_components: ['Padhansahi', 'Khordha', 'Odisha', 'India', '751002'],
    structured_formatting: {
      secondary_text: 'Odisha, India',
      main_text: 'Taragadia',
    },
    description: 'Padhansahi, Odisha, India',
    longitude: 85.7859016,
    latitude: 20.1897333,
  },
  {
    name: 'MORBI',
    place_id: 'ChIJh1ThbNmMWTkRTslAk5ljSCk',
    address_components: ['Morbi', 'Morbi', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Morbi, Gujarat',
      main_text: 'Morbi',
    },
    description: 'Morbi, Morbi, Gujarat',
    longitude: 70.84908089999999,
    latitude: 22.8251874,
  },
  {
    name: 'PADAVLA',
    place_id: 'ChIJ7WSILhuOVzkRqb9Q7fjy0MA',
    address_components: [
      'Padavla Road',
      'Rajkot',
      'Gujarat',
      'India',
      '360450',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Padavla',
    },
    description: 'Padavla Road, Gujarat, India',
    longitude: 70.2490282,
    latitude: 21.880949,
  },
  {
    name: 'CHANDKHEDA',
    place_id: 'ChIJjX9Rl1KCXjkRPd2JXcHLUGA',
    address_components: [
      'Chandkheda',
      'Ahmedabad',
      'Ahmedabad',
      'Gujarat',
      'India',
    ],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Chandkheda',
    },
    description: 'Chandkheda, Ahmedabad, Gujarat',
    longitude: 72.5849179,
    latitude: 23.109098,
  },
  {
    name: 'DESAR',
    place_id: 'ChIJpcVRICUlXjkRmxWjD0W8LLA',
    address_components: ['Desar', 'Vadodara', 'Gujarat', 'India', '391774'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Desar',
    },
    description: 'Desar, Gujarat, India',
    longitude: 73.2926753,
    latitude: 22.7159213,
  },
  {
    name: 'Ribda',
    place_id: 'ChIJ-SzbF9s1WDkRrs2pZ8zBKPk',
    address_components: ['Ribda', 'Rajkot', 'Gujarat', 'India', '360311'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Ribda',
    },
    description: 'Ribda, Gujarat, India',
    longitude: 70.78077689999999,
    latitude: 22.1274677,
  },
  {
    name: 'Kalipat',
    place_id: 'ChIJAzmcbse0WTkRAJH2xqC-fdI',
    address_components: ['Kalipat', 'Rajkot', 'Gujarat', 'India', '360020'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kalipat',
    },
    description: 'Kalipat, Gujarat, India',
    longitude: 70.88260030000001,
    latitude: 22.2363838,
  },
  {
    name: 'Khavda',
    place_id: 'ChIJVSLteK9LUDkRDXxZQW7zRN4',
    address_components: ['Khavda', 'Kutch', 'Gujarat', 'India', '370510'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Khavda',
    },
    description: 'Khavda, Gujarat, India',
    longitude: 69.7316714,
    latitude: 23.8442908,
  },
  {
    name: 'AMRELI',
    place_id: 'ChIJRWhRLceAWDkRErsFtf8MlU4',
    address_components: ['Amreli', 'Amreli', 'Gujarat', 'India', '365601'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Amreli',
    },
    description: 'Amreli, Gujarat, India',
    longitude: 71.2203555,
    latitude: 21.6015242,
  },
  {
    name: 'Himatnagar',
    place_id: 'ChIJQY5jK-m4XTkRwaZH0lU9jmg',
    address_components: ['Himatnagar', 'Sabarkatha', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Sabarkatha, Gujarat',
      main_text: 'Himatnagar',
    },
    description: 'Himatnagar, Sabarkatha, Gujarat',
    longitude: 72.9630378,
    latitude: 23.5968857,
  },
  {
    name: 'Vyara',
    place_id: 'ChIJh1lNJsl-4DsRWii_Yw4x0YY',
    address_components: ['Vyara', 'Tapi', 'Gujarat', 'India', '394650'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Vyara',
    },
    description: 'Vyara, Gujarat, India',
    longitude: 73.3861266,
    latitude: 21.1104293,
  },
  {
    name: 'Moti Khavadi',
    place_id: 'ChIJQ-Hlb19aVzkRG1NvMZ_yAGc',
    address_components: [
      'Moti Khavadi',
      'Jamnagar',
      'Gujarat',
      'India',
      '361011',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Moti Khavadi',
    },
    description: 'Moti Khavadi, Gujarat, India',
    longitude: 70.2973811,
    latitude: 22.6657598,
  },
  {
    name: 'Changodar',
    place_id: 'ChIJdfO_5tqQXjkRcCzm2_Ly1i8',
    address_components: ['Changodar', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Changodar',
    },
    description: 'Changodar, Ahmedabad, Gujarat',
    longitude: 72.43441539999999,
    latitude: 22.9147264,
  },
  {
    name: 'UPLETA',
    place_id: 'ChIJ042ejfnyVzkRtjMeXixKGe0',
    address_components: ['Upleta', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Upleta',
    },
    description: 'Upleta, Rajkot, Gujarat',
    longitude: 70.2795033,
    latitude: 21.7395387,
  },
  {
    name: 'LOTHADA',
    place_id: 'ChIJY5hNrldKWDkRKr-LiW3x26o',
    address_components: ['Lothada', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Lothada',
    },
    description: 'Lothada, Rajkot, Gujarat',
    longitude: 70.85064360000001,
    latitude: 22.1688495,
  },
  {
    name: 'Mehsana',
    place_id: 'ChIJ9Z54ryxCXDkR3Iu-uJC8Cxc',
    address_components: ['Mehsana', 'Mehsana', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Mehsana, Gujarat',
      main_text: 'Mehsana',
    },
    description: 'Mehsana, Mehsana, Gujarat',
    longitude: 72.36932519999999,
    latitude: 23.5879607,
  },
  {
    name: 'Idar',
    place_id: 'ChIJz-ROJfGjXTkRtuLC-SFF9Rs',
    address_components: ['Idar', 'Sabarkatha', 'Gujarat', 'India', '383430'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Idar',
    },
    description: 'Idar, Gujarat, India',
    longitude: 73.0006449,
    latitude: 23.8395124,
  },
  {
    name: 'VALSAD',
    place_id: 'ChIJz6ZJgiDo4DsRE6iVTP0ptvY',
    address_components: ['Valsad', 'Valsad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Valsad, Gujarat',
      main_text: 'Valsad',
    },
    description: 'Valsad, Valsad, Gujarat',
    longitude: 72.9342451,
    latitude: 20.5992349,
  },
  {
    name: 'NANA CHILODA',
    place_id: 'ChIJXbh4rQSBXjkRC0xWa0onzPI',
    address_components: [
      'Nana Chiloda',
      'Ahmedabad',
      'Gandhinagar',
      'Gujarat',
      'India',
    ],
    structured_formatting: {
      secondary_text: 'Gandhinagar, Gujarat',
      main_text: 'Nana Chiloda',
    },
    description: 'Nana Chiloda, Gandhinagar, Gujarat',
    longitude: 72.6596507,
    latitude: 23.1077003,
  },
  {
    name: 'BARODA',
    place_id: 'ChIJq92jkavIXzkRuD9H4b_TOaw',
    address_components: ['Vadodara', 'Vadodara', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Vadodara, Gujarat',
      main_text: 'Baroda',
    },
    description: 'Vadodara, Vadodara, Gujarat',
    longitude: 73.1812187,
    latitude: 22.3071588,
  },
  {
    name: 'RAVKI',
    place_id: 'ChIJbc_FCLA0WDkRQykvod3vWFM',
    address_components: ['Ravki', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Ravki',
    },
    description: 'Ravki, Rajkot, Gujarat',
    longitude: 70.73468869999999,
    latitude: 22.1861889,
  },
  {
    name: 'Odhav',
    place_id: 'ChIJsw_NzpYNXDkR4xIl9ynsIM4',
    address_components: ['Odhav', 'Ahmedabad', 'Gujarat', 'India', '382145'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Odhav',
    },
    description: 'Odhav, Gujarat, India',
    longitude: 72.12680320000001,
    latitude: 23.4110558,
  },
  {
    name: 'BHARUDI',
    place_id: 'ChIJTa0WElc2WDkRZJV_AEIxl98',
    address_components: ['Bharudi', 'Rajkot', 'Gujarat', 'India', '360311'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bharudi',
    },
    description: 'Bharudi, Gujarat, India',
    longitude: 70.7673969,
    latitude: 22.0786543,
  },
  {
    name: 'Bhalgam',
    place_id: 'ChIJww_Q7YkHWDkRfeUfc-Usq54',
    address_components: ['Bhalgam', 'Junagadh', 'Gujarat', 'India', '362110'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bhalgam',
    },
    description: 'Bhalgam, Gujarat, India',
    longitude: 70.59193570000001,
    latitude: 21.4600425,
  },
  {
    name: 'JUNAGADH',
    place_id: 'ChIJU38naowBWDkRSG6oIIUvtRM',
    address_components: ['Junagadh', 'Junagadh', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Junagadh, Gujarat',
      main_text: 'Junagadh',
    },
    description: 'Junagadh, Junagadh, Gujarat',
    longitude: 70.4579436,
    latitude: 21.5222203,
  },
  {
    name: 'Bamanbor',
    place_id: 'ChIJf6yzq4WvWTkR1gYjt1gKXLY',
    address_components: ['Bamanbor', 'Rajkot', 'Gujarat', 'India', '363520'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bamanbor',
    },
    description: 'Bamanbor, Gujarat, India',
    longitude: 71.0412338,
    latitude: 22.4155343,
  },
  {
    name: 'UNCHADI',
    place_id: 'ChIJCz3SmlGL4TsRMkUbk_rGkg4',
    address_components: ['Unchadi', 'Bhavnagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Bhavnagar, Gujarat',
      main_text: 'Unchadi',
    },
    description: 'Unchadi, Bhavnagar, Gujarat',
    longitude: 72.0379277,
    latitude: 21.2447405,
  },
  {
    name: 'SARGASAN',
    place_id: 'ChIJ-SwpQiAqXDkRmI4a-68yJD0',
    address_components: [
      'Sargasan',
      'Gandhinagar',
      'Gandhinagar',
      'Gujarat',
      'India',
    ],
    structured_formatting: {
      secondary_text: 'Gandhinagar, Gujarat',
      main_text: 'Sargasan',
    },
    description: 'Sargasan, Gandhinagar, Gujarat',
    longitude: 72.6155634,
    latitude: 23.1929497,
  },
  {
    name: 'SURAT',
    place_id: 'ChIJYxUdQVlO4DsRQrA4CSlYRf4',
    address_components: ['Surat', 'Surat', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Surat, Gujarat',
      main_text: 'Surat',
    },
    description: 'Surat, Surat, Gujarat',
    longitude: 72.83106070000001,
    latitude: 21.1702401,
  },
  {
    name: 'CHAPARA',
    place_id: 'ChIJ8fpjOtT-PDoRqY3OrHBx9CY',
    address_components: ['Chapara', 'Srikakulam', 'Andhra Pradesh', 'India'],
    structured_formatting: {
      secondary_text: 'Srikakulam, Andhra Pradesh',
      main_text: 'Chapara',
    },
    description: 'Chapara, Srikakulam, Andhra Pradesh',
    longitude: 84.1870297,
    latitude: 18.7723899,
  },
  {
    name: 'BAVLA',
    place_id: 'ChIJ3VjsurCVXjkRjTmNgdxkuVA',
    address_components: ['Bavla', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Bavla',
    },
    description: 'Bavla, Ahmedabad, Gujarat',
    longitude: 72.3627976,
    latitude: 22.8365498,
  },
  {
    name: 'MAKHAVAD',
    place_id: 'ChIJH-i3lZwzWDkRqRJrSxs9UbE',
    address_components: ['Makhavad', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Makhavad',
    },
    description: 'Makhavad, Rajkot, Gujarat',
    longitude: 70.6990045,
    latitude: 22.1475178,
  },
  {
    name: 'ANANDPAR',
    place_id: 'ChIJ63JxkAzGWTkRqjlzc6CvMmE',
    address_components: ['Anandpar', 'Rajkot', 'Gujarat', 'India', '360003'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Anandpar',
    },
    description: 'Anandpar, Gujarat, India',
    longitude: 70.73468869999999,
    latitude: 22.4034891,
  },
  {
    name: 'Modhuka',
    place_id: 'ChIJP2yfAGHlWDkRVIRncPLC6ao',
    address_components: ['Modhuka', 'Rajkot', 'Gujarat', 'India', '360055'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Modhuka',
    },
    description: 'Modhuka, Gujarat, India',
    longitude: 71.412125,
    latitude: 22.1069437,
  },
  {
    name: 'DEHGAM',
    place_id: 'ChIJNUwvxrp4XjkRWcjMnPmafTo',
    address_components: [
      'Dahegam',
      'Gandhinagar',
      'Gujarat',
      'India',
      '382305',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Dehgam',
    },
    description: 'Dahegam, Gujarat, India',
    longitude: 72.81024500000001,
    latitude: 23.1637196,
  },
  {
    name: 'Kheda',
    place_id: 'ChIJg1z2ZqD1XjkR-IuGkUVqzx8',
    address_components: ['Kheda', 'Kheda', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kheda, Gujarat',
      main_text: 'Kheda',
    },
    description: 'Kheda, Kheda, Gujarat',
    longitude: 72.68466579999999,
    latitude: 22.750651,
  },
  {
    name: 'Anand',
    place_id: 'ChIJhYgM_X5OXjkRFVJLDDy5oKk',
    address_components: ['Anand', 'Anand', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Anand, Gujarat',
      main_text: 'Anand',
    },
    description: 'Anand, Anand, Gujarat',
    longitude: 72.928871,
    latitude: 22.5645175,
  },
  {
    name: 'Vadnagar',
    place_id: 'ChIJWUBM3ZRTXDkRQwoUUW90Vx0',
    address_components: ['Vadnagar', 'Mehsana', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Mehsana, Gujarat',
      main_text: 'Vadnagar',
    },
    description: 'Vadnagar, Mehsana, Gujarat',
    longitude: 72.6165643,
    latitude: 23.7757259,
  },
  {
    name: 'DHOLERA',
    place_id: 'ChIJ-QBB_1EkXzkRrQ4RIC_VLKo',
    address_components: ['Dholera', 'Ahmedabad', 'Gujarat', 'India', '382455'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Dholera',
    },
    description: 'Dholera, Gujarat, India',
    longitude: 72.1934421,
    latitude: 22.2498636,
  },
  {
    name: 'HARIPAR',
    place_id: 'ChIJld-gxrzcWTkRp6qBTyvfha8',
    address_components: ['Haripar', 'Rajkot', 'Gujarat', 'India', '360110'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Haripar',
    },
    description: 'Haripar, Gujarat, India',
    longitude: 70.6023462,
    latitude: 22.4742866,
  },
  {
    name: 'Pipavav',
    place_id: 'ChIJo1yLCNRJ4jsRLMbIvhWzBZ4',
    address_components: ['Pipavav', 'Amreli', 'Gujarat', 'India', '365555'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Pipavav',
    },
    description: 'Pipavav, Gujarat, India',
    longitude: 71.5341894,
    latitude: 21.0120728,
  },
  {
    name: 'SANTRAMPUR',
    place_id: 'ChIJFweMxXDJYDkRSihK205aW3M',
    address_components: [
      'Santrampur',
      'Mahisagar',
      'Gujarat',
      'India',
      '389260',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Santrampur',
    },
    description: 'Santrampur, Gujarat, India',
    longitude: 73.8962994,
    latitude: 23.1908041,
  },
  {
    name: 'GONDAL',
    place_id: 'ChIJDXeoG5A4WDkRO8aovstfYGg',
    address_components: ['Gondal', 'Rajkot', 'Gujarat', 'India', '360311'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Gondal',
    },
    description: 'Gondal, Gujarat, India',
    longitude: 70.7938777,
    latitude: 21.9611708,
  },
  {
    name: 'TANKARA',
    place_id: 'ChIJO76W8ofrWTkRlWL5u4gHvo0',
    address_components: ['Tankara', 'Rajkot', 'Gujarat', 'India', '363650'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Tankara',
    },
    description: 'Tankara, Gujarat, India',
    longitude: 70.7480696,
    latitude: 22.6553114,
  },
  {
    name: 'Maliya',
    place_id: 'ChIJxf063LAZWjkR985t7zAcPTc',
    address_components: ['Malia', 'Rajkot', 'Gujarat', 'India', '363670'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Maliya',
    },
    description: 'Malia, Gujarat, India',
    longitude: 70.7593481,
    latitude: 23.0923852,
  },
  {
    name: 'Dahej',
    place_id: 'ChIJhwd1pLh9XzkROLtbxDUJDpI',
    address_components: ['Dahej', 'Bharuch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Bharuch, Gujarat',
      main_text: 'Dahej',
    },
    description: 'Dahej, Bharuch, Gujarat',
    longitude: 72.58200900000001,
    latitude: 21.7129335,
  },
  {
    name: 'Ronki',
    place_id: 'ChIJqd3L783JWTkRFzrOn1clZF4',
    address_components: ['Ronki', 'Rajkot', 'Gujarat', 'India', '360006'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Ronki',
    },
    description: 'Ronki, Gujarat, India',
    longitude: 70.7993595,
    latitude: 22.3435164,
  },
  {
    name: 'HALOL',
    place_id: 'ChIJWx_I8_B_YDkRZbk4EJ-UUvQ',
    address_components: ['Halol', 'Panchmahal', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Panchmahal, Gujarat',
      main_text: 'Halol',
    },
    description: 'Halol, Panchmahal, Gujarat',
    longitude: 73.4713666,
    latitude: 22.5045713,
  },
  {
    name: 'MOTERA',
    place_id: 'ChIJTxIjdsODXjkRiCMOQDvxt24',
    address_components: [
      'Motera',
      'Ahmedabad',
      'Ahmedabad',
      'Gujarat',
      'India',
    ],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Motera',
    },
    description: 'Motera, Ahmedabad, Gujarat',
    longitude: 72.6028979,
    latitude: 23.1048808,
  },
  {
    name: 'Kadi',
    place_id: 'ChIJj-IhgwcYXDkRHFeJSS8pqdw',
    address_components: ['Kadi', 'Mehsana', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Mehsana, Gujarat',
      main_text: 'Kadi',
    },
    description: 'Kadi, Mehsana, Gujarat',
    longitude: 72.33024209999999,
    latitude: 23.2973208,
  },
  {
    name: 'Bhunava',
    place_id: 'ChIJ056miqM3WDkRfdc--_4MhK8',
    address_components: ['Bhunava', 'Rajkot', 'Gujarat', 'India', '360311'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bhunava',
    },
    description: 'Bhunava, Gujarat, India',
    longitude: 70.7703703,
    latitude: 22.0532778,
  },
  {
    name: 'PIPALANA',
    place_id: 'ChIJRwiclTT9VzkR8u1-bACsWvQ',
    address_components: ['Pipalana', 'Junagadh', 'Gujarat', 'India', '362630'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Pipalana',
    },
    description: 'Pipalana, Gujarat, India',
    longitude: 70.2415766,
    latitude: 21.4397444,
  },
  {
    name: 'Metoda',
    place_id: 'ChIJFy3kiwbNWTkRGXfnUzxtpOQ',
    address_components: ['Metoda', 'Rajkot', 'Gujarat', 'India', '360021'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Metoda',
    },
    description: 'Metoda, Gujarat, India',
    longitude: 70.6618305,
    latitude: 22.2358644,
  },
  {
    name: 'KUVADVA',
    place_id: 'ChIJdb6VnwSxWTkRheFXPDnGPZQ',
    address_components: ['Kuvadva', 'Rajkot', 'Gujarat', 'India', '360023'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kuvadva',
    },
    description: 'Kuvadva, Gujarat, India',
    longitude: 70.9441441,
    latitude: 22.359551,
  },
  {
    name: 'BHALGAM',
    place_id: 'ChIJV-zOw6uf4jsRxWm1zNx1OfI',
    address_components: [
      'Bhalgam',
      'Visavadar',
      'Junagadh',
      'Gujarat',
      'India',
      '362130',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bhalgam',
    },
    description: 'Bhalgam, Gujarat, India',
    longitude: 70.8543596,
    latitude: 21.441969,
  },
  {
    name: 'CHAMPAVADI',
    place_id: 'ChIJYbJGQ5d54DsRR1D_quQN09s',
    address_components: ['Champavadi', 'Tapi', 'Gujarat', 'India', '394651'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Champavadi',
    },
    description: 'Champavadi, Gujarat, India',
    longitude: 73.3885526,
    latitude: 21.1819116,
  },
  {
    name: 'UNJHA',
    place_id: 'ChIJI8kLqZJeXDkRGfSKA97tRow',
    address_components: ['Unjha', 'Mehsana', 'Gujarat', 'India', '384170'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Unjha',
    },
    description: 'Unjha, Gujarat, India',
    longitude: 72.3902277,
    latitude: 23.8035004,
  },
  {
    name: 'PETHAPUR',
    place_id: 'ChIJSY91GDYsXDkRQ8I-0J8Gs1k',
    address_components: [
      'Pethapur',
      'Gandhinagar',
      'Gandhinagar',
      'Gujarat',
      'India',
    ],
    structured_formatting: {
      secondary_text: 'Gandhinagar, Gujarat',
      main_text: 'Pethapur',
    },
    description: 'Pethapur, Gandhinagar, Gujarat',
    longitude: 72.67208040000001,
    latitude: 23.2642743,
  },
  {
    name: 'Mubarakpur',
    place_id: 'ChIJY6JbJV8tXDkR9_YfxdGf8U8',
    address_components: [
      'Mubarakpur',
      'Gandhinagar',
      'Gujarat',
      'India',
      '382735',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Mubarakpur',
    },
    description: 'Mubarakpur, Gujarat, India',
    longitude: 72.6912425,
    latitude: 23.3503825,
  },
  {
    name: 'Nichi Mandal',
    place_id: 'ChIJLfFIHyGPWTkR8PEQ_l6g3nw',
    address_components: ['Nichimandal', 'Rajkot', 'Gujarat', 'India', '363641'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Nichi Mandal',
    },
    description: 'Nichimandal, Gujarat, India',
    longitude: 70.9641262,
    latitude: 22.8621108,
  },
  {
    name: 'Bhuj',
    place_id: 'ChIJF28LAAniUDkRpnQHr1jzd3A',
    address_components: ['Bhuj', 'Kutch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kutch, Gujarat',
      main_text: 'Bhuj',
    },
    description: 'Bhuj, Kutch, Gujarat',
    longitude: 69.6669324,
    latitude: 23.2419997,
  },
  {
    name: 'Pethapur',
    place_id: 'ChIJ3c8RLHceXTkRyBuoXu3zSYI',
    address_components: ['Pethapur', 'Banaskantha', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Banaskantha, Gujarat',
      main_text: 'Pethapur',
    },
    description: 'Pethapur, Banaskantha, Gujarat',
    longitude: 72.74222639999999,
    latitude: 24.196039,
  },
  {
    name: 'JAMJODHPUR',
    place_id: 'ChIJvTmYf2q9VzkRXKTx9vLbAfo',
    address_components: [
      'Jamjodhpur',
      'Jamnagar',
      'Gujarat',
      'India',
      '360530',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Jamjodhpur',
    },
    description: 'Jamjodhpur, Gujarat, India',
    longitude: 70.0337715,
    latitude: 21.9025447,
  },
  {
    name: 'LAKHAPAR',
    place_id: 'ChIJf2b-8M-_UDkRjZUMLNfV-Ag',
    address_components: ['Lakhapar', 'Kutch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kutch, Gujarat',
      main_text: 'Lakhapar',
    },
    description: 'Lakhapar, Kutch, Gujarat',
    longitude: 70.0919949,
    latitude: 23.2009429,
  },
  {
    name: 'JAROD',
    place_id: 'ChIJcU4DCLfTXzkRxeXIaA-2-Vk',
    address_components: ['Jarod', 'Vadodara', 'Gujarat', 'India', '391510'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Jarod',
    },
    description: 'Jarod, Gujarat, India',
    longitude: 73.3340254,
    latitude: 22.4377209,
  },
  {
    name: 'Vadali',
    place_id: 'ChIJAQJ6boCgXTkR-XGdKfr-9-E',
    address_components: ['Vadali', 'Sabarkatha', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Sabarkatha, Gujarat',
      main_text: 'Vadali',
    },
    description: 'Vadali, Sabarkatha, Gujarat',
    longitude: 73.0375761,
    latitude: 23.9419984,
  },
  {
    name: 'KARJAN',
    place_id: 'ChIJN_jEIgXrXzkRbZOxNgY6rZ8',
    address_components: ['Karjan', 'Vadodara', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Vadodara, Gujarat',
      main_text: 'Karjan',
    },
    description: 'Karjan, Vadodara, Gujarat',
    longitude: 73.1201988,
    latitude: 22.0534997,
  },
  {
    name: 'Khambhat',
    place_id: 'ChIJr0bqtaYGXzkRTYXgdwKV7E0',
    address_components: ['Khambhat', 'Anand', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Anand, Gujarat',
      main_text: 'Khambhat',
    },
    description: 'Khambhat, Anand, Gujarat',
    longitude: 72.6189845,
    latitude: 22.3180817,
  },
  {
    name: 'TALOD',
    place_id: 'ChIJvxfgehzbXTkRd5gfY8jBU-U',
    address_components: ['Talod', 'Sabarkatha', 'Gujarat', 'India', '383215'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Talod',
    },
    description: 'Talod, Gujarat, India',
    longitude: 72.9504954,
    latitude: 23.3512271,
  },
  {
    name: 'Mundra',
    place_id: 'ChIJP6RyK-XUUDkRK7CCO16rhDI',
    address_components: ['Mundra', 'Kutch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kutch, Gujarat',
      main_text: 'Mundra',
    },
    description: 'Mundra, Kutch, Gujarat',
    longitude: 69.7213266,
    latitude: 22.8395202,
  },
  {
    name: 'MODHERA',
    place_id: 'ChIJvYWJKh5uXDkRwb8BxhUCcGg',
    address_components: ['Modhera', 'Mehsana', 'Gujarat', 'India', '384212'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Modhera',
    },
    description: 'Modhera, Gujarat, India',
    longitude: 72.1401322,
    latitude: 23.5835819,
  },
  {
    name: 'DUDHAI',
    place_id: 'ChIJBWZ0qOUJeTkRaK88egy-vp8',
    address_components: ['Dudhai', 'Lalitpur', 'Uttar Pradesh', 'India'],
    structured_formatting: {
      secondary_text: 'Lalitpur, Uttar Pradesh',
      main_text: 'Dudhai',
    },
    description: 'Dudhai, Lalitpur, Uttar Pradesh',
    longitude: 78.3899108,
    latitude: 24.4372886,
  },
  {
    name: 'PADHARI',
    place_id: 'ChIJwYlcLuf68zkRqSVaFlF7aCk',
    address_components: [
      'Duar Padhari',
      'Giridih',
      'Jharkhand',
      'India',
      '815316',
    ],
    structured_formatting: {
      secondary_text: 'Jharkhand, India',
      main_text: 'Padhari',
    },
    description: 'Duar Padhari, Jharkhand, India',
    longitude: 86.12683369999999,
    latitude: 24.2582895,
  },
  {
    name: 'DHORAJI',
    place_id: 'ChIJr3QEVhYeWDkRc6FFN0Nj1zs',
    address_components: ['Dhoraji', 'Rajkot', 'Gujarat', 'India', '360410'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Dhoraji',
    },
    description: 'Dhoraji, Gujarat, India',
    longitude: 70.4491417,
    latitude: 21.7398165,
  },
  {
    name: 'JABALPUR',
    place_id: 'ChIJfam2DxqugTkRueNDvBYGAkQ',
    address_components: ['Jabalpur', 'Jabalpur', 'Madhya Pradesh', 'India'],
    structured_formatting: {
      secondary_text: 'Jabalpur, Madhya Pradesh',
      main_text: 'Jabalpur',
    },
    description: 'Jabalpur, Jabalpur, Madhya Pradesh',
    longitude: 79.9864071,
    latitude: 23.181467,
  },
  {
    name: 'SHANKHESHWAR',
    place_id: 'ChIJez1yhMKNWzkRsMTxdQR_PDc',
    address_components: ['Shankheshwar', 'Patan', 'Gujarat', 'India', '384246'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Shankheshwar',
    },
    description: 'Shankheshwar, Gujarat, India',
    longitude: 71.7919027,
    latitude: 23.5061743,
  },
  {
    name: 'KODINAR',
    place_id: 'ChIJMTCDxTrZ4jsRreql6bdvkUg',
    address_components: ['Kodinar', 'Junagadh', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Junagadh, Gujarat',
      main_text: 'Kodinar',
    },
    description: 'Kodinar, Junagadh, Gujarat',
    longitude: 70.6960306,
    latitude: 20.8009246,
  },
  {
    name: 'MAHUVA',
    place_id: 'ChIJeRE7jNUk4jsR94LmrW8w3o0',
    address_components: ['Mahuva', 'Bhavnagar', 'Gujarat', 'India', '364290'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Mahuva',
    },
    description: 'Mahuva, Gujarat, India',
    longitude: 71.7704631,
    latitude: 21.0921598,
  },
  {
    name: 'BHARUCH',
    place_id: 'ChIJIcQqsqIg4DsRKv0iRkJsEaQ',
    address_components: ['Bharuch', 'Bharuch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Bharuch, Gujarat',
      main_text: 'Bharuch',
    },
    description: 'Bharuch, Bharuch, Gujarat',
    longitude: 72.9958748,
    latitude: 21.7051358,
  },
  {
    name: 'SANAND',
    place_id: 'ChIJ1b5QS6qZXjkRbTk2-hn-5ZU',
    address_components: ['Sanand', 'Ahmedabad', 'Gujarat', 'India', '382110'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Sanand',
    },
    description: 'Sanand, Gujarat, India',
    longitude: 72.3772986,
    latitude: 22.9919637,
  },
  {
    name: 'BHACHAU',
    place_id: 'ChIJi5Pe9jqfUDkROBxjcXDHiHI',
    address_components: ['Bhachau', 'Kutch', 'Gujarat', 'India', '370140'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bhachau',
    },
    description: 'Bhachau, Gujarat, India',
    longitude: 70.339045,
    latitude: 23.2930388,
  },
  {
    name: 'DWARKA',
    place_id: 'ChIJe-OZYyacVjkRCm4QGkZuhrU',
    address_components: ['Dwarka', 'Jamnagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Jamnagar, Gujarat',
      main_text: 'Dwarka',
    },
    description: 'Dwarka, Jamnagar, Gujarat',
    longitude: 68.96845619999999,
    latitude: 22.2441975,
  },
  {
    name: 'Sankheda',
    place_id: 'ChIJB0jIMUdzYDkR-FPgWMpSxEk',
    address_components: ['Sankheda', 'Vadodara', 'Gujarat', 'India', '391145'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Sankheda',
    },
    description: 'Sankheda, Gujarat, India',
    longitude: 73.5814967,
    latitude: 22.1715494,
  },
  {
    name: 'WAGHODIYA',
    place_id: 'ChIJSW3z2-TZXzkRZ3uw8dC2qfI',
    address_components: [
      'Vaghodia INA',
      'Vadodara',
      'Gujarat',
      'India',
      '391760',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Waghodiya',
    },
    description: 'Vaghodia INA, Gujarat, India',
    longitude: 73.384132,
    latitude: 22.3100632,
  },
  {
    name: 'MODASA',
    place_id: 'ChIJ68Dh-DXwXTkRmzayb7Loj2U',
    address_components: ['Modasa', 'Aravalli', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Aravalli, Gujarat',
      main_text: 'Modasa',
    },
    description: 'Modasa, Aravalli, Gujarat',
    longitude: 73.29875779999999,
    latitude: 23.464311,
  },
  {
    name: 'KANGHSHIYALI',
    place_id: 'ChIJw4FDfzU1WDkRQcb4yPrJFzQ',
    address_components: ['Rajkot', 'Rajkot', 'Gujarat', 'India', '360022'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kanghshiyali',
    },
    description: 'Rajkot, Gujarat, India',
    longitude: 70.7879091,
    latitude: 22.2070399,
  },
  {
    name: 'NAVLAKHI',
    place_id: 'ChIJi1T9g-gAWjkRYi9wSrJZwbE',
    address_components: ['Navlakhi', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Navlakhi',
    },
    description: 'Navlakhi, Rajkot, Gujarat',
    longitude: 70.4967441,
    latitude: 22.9565796,
  },
  {
    name: 'NANA PONDHA',
    place_id: 'ChIJUX6LaK634DsRvca04akBn3w',
    address_components: ['Nana Pondha', 'Valsad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Valsad, Gujarat',
      main_text: 'Nana Pondha',
    },
    description: 'Nana Pondha, Valsad, Gujarat',
    longitude: 73.12905959999999,
    latitude: 20.4053386,
  },
  {
    name: 'Ughrojpura',
    place_id: 'ChIJc1kb4IsOXDkRmfqF-99M2dk',
    address_components: [
      'Ughrojpura',
      'Ahmedabad',
      'Gujarat',
      'India',
      '382120',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Ughrojpura',
    },
    description: 'Ughrojpura, Gujarat, India',
    longitude: 72.0882938,
    latitude: 23.3576801,
  },
  {
    name: 'JAMKHAMBALIYA',
    place_id: 'ChIJ3wCM4nP9VjkRsoxdYnVNbb4',
    address_components: [
      'Khambhalia',
      'Jamnagar',
      'Gujarat',
      'India',
      '361305',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Jamkhambaliya',
    },
    description: 'Khambhalia, Gujarat, India',
    longitude: 69.6587765,
    latitude: 22.2052603,
  },
  {
    name: 'Samana',
    place_id: 'ChIJ8U8qAbmdVzkRS5YK_bzoq7M',
    address_components: ['Samana', 'Jamnagar', 'Gujarat', 'India', '360520'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Samana',
    },
    description: 'Samana, Gujarat, India',
    longitude: 70.1626972,
    latitude: 22.104557,
  },
  {
    name: 'Patan',
    place_id: 'ChIJlVYRX5KHXDkRzvlPfAmxHW8',
    address_components: ['Patan', 'Patan', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Patan, Gujarat',
      main_text: 'Patan',
    },
    description: 'Patan, Patan, Gujarat',
    longitude: 72.1210274,
    latitude: 23.8500156,
  },
  {
    name: 'MUMBAI',
    place_id: 'ChIJwe1EZjDG5zsRaYxkjY_tpF0',
    address_components: ['Mumbai', 'Mumbai', 'Maharashtra', 'India'],
    structured_formatting: {
      secondary_text: 'Mumbai, Maharashtra',
      main_text: 'Mumbai',
    },
    description: 'Mumbai, Mumbai, Maharashtra',
    longitude: 72.8776559,
    latitude: 19.0759837,
  },
  {
    name: 'VATVA',
    place_id: 'ChIJZXBEn56IXjkRCK9bS1hVqHU',
    address_components: ['Vatva', 'Ahmedabad', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Vatva',
    },
    description: 'Vatva, Ahmedabad, Gujarat',
    longitude: 72.6159326,
    latitude: 22.9664255,
  },
  {
    name: 'Shinay',
    place_id: 'ChIJea_vfAS4UDkRTmf0f9vrjzs',
    address_components: ['Shinay', 'Kutch', 'Gujarat', 'India', '370205'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Shinay',
    },
    description: 'Shinay, Gujarat, India',
    longitude: 70.0570129,
    latitude: 23.0375083,
  },
  {
    name: 'Surendranagar',
    place_id: 'ChIJr4Kf3N9AWTkRQz33i4tXsqQ',
    address_components: ['Surendranagar', 'Surendranagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Surendranagar, Gujarat',
      main_text: 'Surendranagar',
    },
    description: 'Surendranagar, Surendranagar, Gujarat',
    longitude: 71.63695419999999,
    latitude: 22.7251204,
  },
  {
    name: 'DHANGADHRA',
    place_id: 'ChIJjxXwbGliWTkRBlyGc1en2nk',
    address_components: [
      'Dhrangdhra',
      'Mayurnagar',
      'Dhrangadhra',
      'Surendranagar',
      'Gujarat',
      'India',
      '363310',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Dhangadhra',
    },
    description: 'Dhrangdhra, Gujarat, India',
    longitude: 71.4461068,
    latitude: 23.003354,
  },
  {
    name: 'Kangsiyali',
    place_id: 'ChIJdbAGtjM1WDkRSJZ0X7RviCo',
    address_components: ['Kangsiyali', 'Rajkot', 'Gujarat', 'India', '360024'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kangsiyali',
    },
    description: 'Kangsiyali, Gujarat, India',
    longitude: 70.7800336,
    latitude: 22.2053083,
  },
  {
    name: 'Hadmatala',
    place_id: 'ChIJrX1xRhHYWDkRpOKHVE92kCY',
    address_components: [
      'Hadmatala',
      'Ahmedabad',
      'Gujarat',
      'India',
      '382255',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Hadmatala',
    },
    description: 'Hadmatala, Gujarat, India',
    longitude: 71.7451955,
    latitude: 22.3071769,
  },
  {
    name: 'Dudhai',
    place_id: 'ChIJ60qlPY2TUDkRTw52LhQNAaw',
    address_components: ['Dudhai', 'Kutch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kutch, Gujarat',
      main_text: 'Dudhai',
    },
    description: 'Dudhai, Kutch, Gujarat',
    longitude: 70.1306961,
    latitude: 23.3228515,
  },
  {
    name: 'Sihor',
    place_id: 'ChIJPfCHVaFUXzkR5aptu13c9Qk',
    address_components: ['Sihor', 'Bhavnagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Bhavnagar, Gujarat',
      main_text: 'Sihor',
    },
    description: 'Sihor, Bhavnagar, Gujarat',
    longitude: 71.9597023,
    latitude: 21.7197378,
  },
  {
    name: 'Bhimasar',
    place_id: 'ChIJA2lus8i9UDkRH77L-hw4Vw0',
    address_components: ['Bhimasar', 'Kutch', 'Gujarat', 'India', '370240'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bhimasar',
    },
    description: 'Bhimasar, Gujarat, India',
    longitude: 70.1649298,
    latitude: 23.1919624,
  },
  {
    name: 'Rajula',
    place_id: 'ChIJW9023bBF4jsRN11LhK2IAE4',
    address_components: ['Rajula', 'Amreli', 'Gujarat', 'India', '365560'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Rajula',
    },
    description: 'Rajula, Gujarat, India',
    longitude: 71.4488241,
    latitude: 21.0411065,
  },
  {
    name: 'Kapadvanj',
    place_id: 'ChIJdeFtk1htXjkRcXwdGfgEI7c',
    address_components: ['Kapadvanj', 'Kheda', 'Gujarat', 'India', '387620'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kapadvanj',
    },
    description: 'Kapadvanj, Gujarat, India',
    longitude: 73.0700421,
    latitude: 23.0200163,
  },
  {
    name: 'Pipaliya',
    place_id: 'ChIJTbsFnEM2WDkRmx73j9UggdQ',
    address_components: ['Pipaliya', 'Rajkot', 'Gujarat', 'India', '360311'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Pipaliya',
    },
    description: 'Pipaliya, Gujarat, India',
    longitude: 70.7771733,
    latitude: 22.0945122,
  },
  {
    name: 'Lodhika',
    place_id: 'ChIJhX_GA3AyWDkRw8PJyZA878I',
    address_components: ['Lodhika', 'Rajkot', 'Gujarat', 'India', '360035'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Lodhika',
    },
    description: 'Lodhika, Gujarat, India',
    longitude: 70.6328328,
    latitude: 22.1344105,
  },
  {
    name: 'Shilaj',
    place_id: 'ChIJzdooTX6cXjkRq2cmuY6DFRE',
    address_components: ['Shilaj', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Shilaj',
    },
    description: 'Shilaj, Ahmedabad, Gujarat',
    longitude: 72.4686607,
    latitude: 23.0557134,
  },
  {
    name: 'Gadu',
    place_id: 'ChIJm4ctTNVJ_TsRpYSG2j-2ySQ',
    address_components: ['Gadu', 'Junagadh', 'Gujarat', 'India', '362250'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Gadu',
    },
    description: 'Gadu, Gujarat, India',
    longitude: 70.2910273,
    latitude: 21.0538131,
  },
  {
    name: 'KALOL',
    place_id: 'ChIJY_aLwOYlXDkRhrOuImrklP8',
    address_components: ['Kalol', 'Gandhinagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Gandhinagar, Gujarat',
      main_text: 'Kalol',
    },
    description: 'Kalol, Gandhinagar, Gujarat',
    longitude: 72.49297159999999,
    latitude: 23.2418194,
  },
  {
    name: 'KHIRSHARA',
    place_id: 'ChIJO8NSsaVnUTkRcbMotRKDLDQ',
    address_components: ['Khirasara', 'Kutch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kutch, Gujarat',
      main_text: 'Khirshara',
    },
    description: 'Khirasara, Kutch, Gujarat',
    longitude: 69.04616399999999,
    latitude: 23.1148954,
  },
  {
    name: 'Mahijda',
    place_id: 'ChIJzfSIDXWNXjkRbC32CgOqhXE',
    address_components: ['Mahijda', 'Ahmedabad', 'Gujarat', 'India', '382425'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Mahijda',
    },
    description: 'Mahijda, Gujarat, India',
    longitude: 72.5426657,
    latitude: 22.8274309,
  },
  {
    name: 'Jhagadia',
    place_id: 'ChIJORT1HD8e4DsRRp9ANme02tU',
    address_components: ['Jhagadia', 'Bharuch', 'Gujarat', 'India', '393110'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Jhagadia',
    },
    description: 'Jhagadia, Gujarat, India',
    longitude: 73.14975489999999,
    latitude: 21.719148,
  },
  {
    name: 'Kalavad',
    place_id: 'ChIJw22_nP1-VzkRm626A4LIaSc',
    address_components: ['Kalavad', 'Jamnagar', 'Gujarat', 'India', '361160'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kalavad',
    },
    description: 'Kalavad, Gujarat, India',
    longitude: 70.38070580000002,
    latitude: 22.2081932,
  },
  {
    name: 'Chaprada',
    place_id: 'ChIJDy33uTKk4jsRWOASsdP5Sjw',
    address_components: ['Chaprada', 'Junagadh', 'Gujarat', 'India', '362120'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Chaprada',
    },
    description: 'Chaprada, Gujarat, India',
    longitude: 70.6699087,
    latitude: 21.3588148,
  },
  {
    name: 'Gandhidham',
    place_id: 'ChIJlw3si465UDkR4PboLlLLbJ0',
    address_components: ['Gandhidham', 'Kutch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kutch, Gujarat',
      main_text: 'Gandhidham',
    },
    description: 'Gandhidham, Kutch, Gujarat',
    longitude: 70.133673,
    latitude: 23.075297,
  },
  {
    name: 'Vadadala',
    place_id: 'ChIJy-r73PsZXjkRX_yDlkwgj70',
    address_components: ['Vadadala', 'Kheda', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kheda, Gujarat',
      main_text: 'Vadadala',
    },
    description: 'Vadadala, Kheda, Gujarat',
    longitude: 73.28243309999999,
    latitude: 22.9507327,
  },
  {
    name: 'Bajipura',
    place_id: 'ChIJm-PuhbN84DsRqf89RCouo0c',
    address_components: ['Bajipura', 'Tapi', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Tapi, Gujarat',
      main_text: 'Bajipura',
    },
    description: 'Bajipura, Tapi, Gujarat',
    longitude: 73.2794846,
    latitude: 21.0929278,
  },
  {
    name: 'WAGHAI',
    place_id: 'ChIJiWGlgDAn3jsRtACcxNh_9zo',
    address_components: ['Waghai', 'Dang', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Dang, Gujarat',
      main_text: 'Waghai',
    },
    description: 'Waghai, Dang, Gujarat',
    longitude: 73.4975656,
    latitude: 20.7737289,
  },
  {
    name: 'Hathijan',
    place_id: 'ChIJc5nT_1aIXjkRrvzqm3a3F-4',
    address_components: ['Hathijan', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Hathijan',
    },
    description: 'Hathijan, Ahmedabad, Gujarat',
    longitude: 72.6654211,
    latitude: 22.9393789,
  },
  {
    name: 'Mandvi',
    place_id: 'ChIJCz66EzA0UTkRD-E97f-wuoI',
    address_components: ['Mandvi', 'Kutch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kutch, Gujarat',
      main_text: 'Mandvi',
    },
    description: 'Mandvi, Kutch, Gujarat',
    longitude: 69.3554783,
    latitude: 22.833334,
  },
  {
    name: 'Chandkhed',
    place_id: 'ChIJbU_nCFalwjsR_HMbrrVTpyc',
    address_components: ['Chandkhed', 'Pune', 'Maharashtra', 'India', '410506'],
    structured_formatting: {
      secondary_text: 'Maharashtra, India',
      main_text: 'Chandkhed',
    },
    description: 'Chandkhed, Maharashtra, India',
    longitude: 73.64626249999999,
    latitude: 18.6480947,
  },
  {
    name: 'Anjar',
    place_id: 'ChIJH8LLsbTAUDkRumr_vlu5m9A',
    address_components: ['Anjar', 'Kutch', 'Gujarat', 'India', '370110'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Anjar',
    },
    description: 'Anjar, Gujarat, India',
    longitude: 70.0281023,
    latitude: 23.1166716,
  },
  {
    name: 'Khambha',
    place_id: 'ChIJq1EAsUde4jsRgcil7sUXKNQ',
    address_components: ['Khambha', 'Amreli', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Amreli, Gujarat',
      main_text: 'Khambha',
    },
    description: 'Khambha, Amreli, Gujarat',
    longitude: 71.2547534,
    latitude: 21.1399472,
  },
  {
    name: 'Veraval',
    place_id: 'ChIJW6uWiTAy_TsRd6e_CRtHhfI',
    address_components: ['Veraval', 'Junagadh', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Junagadh, Gujarat',
      main_text: 'Veraval',
    },
    description: 'Veraval, Junagadh, Gujarat',
    longitude: 70.3628516,
    latitude: 20.9158979,
  },
  {
    name: 'Babra',
    place_id: 'ChIJG_MEymiMWDkRxbZP0eUKF4w',
    address_components: ['Babra', 'Amreli', 'Gujarat', 'India', '365421'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Babra',
    },
    description: 'Babra, Gujarat, India',
    longitude: 71.30820779999999,
    latitude: 21.8453485,
  },
  {
    name: 'Umara',
    place_id: 'ChIJQ56ORASLXzkR2DhnAhPjhf4',
    address_components: ['Umara', 'Bharuch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Bharuch, Gujarat',
      main_text: 'Umara',
    },
    description: 'Umara, Bharuch, Gujarat',
    longitude: 73.0493825,
    latitude: 21.7853491,
  },
  {
    name: 'Chapara',
    place_id: 'ChIJOfdospPSWTkR98lh5WlEI1E',
    address_components: ['Chhapra', 'Rajkot', 'Gujarat', 'India', '360021'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Chapara',
    },
    description: 'Chhapra, Gujarat, India',
    longitude: 70.6029934,
    latitude: 22.2186981,
  },
  {
    name: 'Visnagar',
    place_id: 'ChIJq_tbvuBPXDkRO7Rm0f_Rjfw',
    address_components: ['Visnagar', 'Mehsana', 'Gujarat', 'India', '384315'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Visnagar',
    },
    description: 'Visnagar, Gujarat, India',
    longitude: 72.5425606,
    latitude: 23.7023775,
  },
  {
    name: 'RANGPAR',
    place_id: 'ChIJ2YJ1HNWLWTkRm3YwUcHKXPA',
    address_components: ['Rangpar', 'Rajkot', 'Gujarat', 'India', '363641'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Rangpar',
    },
    description: 'Rangpar, Gujarat, India',
    longitude: 70.9011786,
    latitude: 22.9159649,
  },
  {
    name: 'PALANPUR',
    place_id: 'ChIJiTGoOkPpXDkRV7hXN4MIpDY',
    address_components: [
      'Palanpur',
      'Banaskantha',
      'Gujarat',
      'India',
      '385001',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Palanpur',
    },
    description: 'Palanpur, Gujarat, India',
    longitude: 72.434581,
    latitude: 24.1724338,
  },
  {
    name: 'JASDAN',
    place_id: 'ChIJE91cxs_3WDkRfRuz6Q2ffPo',
    address_components: ['Jasdan', 'Rajkot', 'Gujarat', 'India', '360050'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Jasdan',
    },
    description: 'Jasdan, Gujarat, India',
    longitude: 71.2017779,
    latitude: 22.0356088,
  },
  {
    name: 'Nijhar',
    place_id: 'ChIJRYCknPWf3zsRqL3AMJ3pniI',
    address_components: ['Nijhar', 'Tapi', 'Gujarat', 'India', '394370'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Nijhar',
    },
    description: 'Nijhar, Gujarat, India',
    longitude: 74.19771999999999,
    latitude: 21.476559,
  },
  {
    name: 'Waghodia',
    place_id: 'ChIJCe4uWMHZXzkR1WGAObfWYEQ',
    address_components: ['Waghodia', 'Vadodara', 'Gujarat', 'India', '391760'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Waghodia',
    },
    description: 'Waghodia, Gujarat, India',
    longitude: 73.3985737,
    latitude: 22.3036529,
  },
  {
    name: 'Botad',
    place_id: 'ChIJ6SbqP37cWDkRhOTi28Xh3ps',
    address_components: ['Botad', 'Bhavnagar', 'Gujarat', 'India', '364710'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Botad',
    },
    description: 'Botad, Gujarat, India',
    longitude: 71.663622,
    latitude: 22.1722509,
  },
  {
    name: 'Vapi',
    place_id: 'ChIJA2YkASzO4DsRFc6qe-tJbco',
    address_components: ['Vapi', 'Valsad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Valsad, Gujarat',
      main_text: 'Vapi',
    },
    description: 'Vapi, Valsad, Gujarat',
    longitude: 72.9106202,
    latitude: 20.3893155,
  },
  {
    name: 'VIRAMGAM',
    place_id: 'ChIJy1P3yYgBXDkRgAjG1r6q05U',
    address_components: ['Viramgam', 'Ahmedabad', 'Gujarat', 'India', '382150'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Viramgam',
    },
    description: 'Viramgam, Gujarat, India',
    longitude: 72.0535829,
    latitude: 23.1249646,
  },
  {
    name: 'BILIMORA',
    place_id: 'ChIJL0sKPELu4DsRHIniP2DQE-Q',
    address_components: ['Bilimora', 'Navsari', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Navsari, Gujarat',
      main_text: 'Bilimora',
    },
    description: 'Bilimora, Navsari, Gujarat',
    longitude: 72.9823779,
    latitude: 20.7702311,
  },
  {
    name: 'VASTRAL',
    place_id: 'ChIJF5JHds-HXjkRjBrHUwRUUL4',
    address_components: [
      'Vastral',
      'Ahmedabad',
      'Ahmedabad',
      'Gujarat',
      'India',
      '380038',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Vastral',
    },
    description: 'Vastral, Gujarat, India',
    longitude: 72.66599099999999,
    latitude: 22.9978372,
  },
  {
    name: 'Lodra',
    place_id: 'ChIJN9JMJE7LXTkRt_zscCUapOE',
    address_components: ['Lodra', 'Mehsana', 'Gujarat', 'India', '382835'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Lodra',
    },
    description: 'Lodra, Gujarat, India',
    longitude: 72.718583,
    latitude: 23.4622066,
  },
  {
    name: 'Kanbha',
    place_id: 'ChIJN8AT6EF9XjkRrq54MWvwbIg',
    address_components: ['Kanbha', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Kanbha',
    },
    description: 'Kanbha, Ahmedabad, Gujarat',
    longitude: 72.7259718,
    latitude: 23.0121959,
  },
  {
    name: 'Manavadar',
    place_id: 'ChIJg-32V63mVzkRViMWgzyXe7Q',
    address_components: ['Manavadar', 'Junagadh', 'Gujarat', 'India', '362630'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Manavadar',
    },
    description: 'Manavadar, Gujarat, India',
    longitude: 70.1366499,
    latitude: 21.493179,
  },
  {
    name: 'Tramba',
    place_id: 'ChIJ7eomp1WzWTkR8T75XsZ0VRs',
    address_components: ['Tramba', 'Rajkot', 'Gujarat', 'India', '360020'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Tramba',
    },
    description: 'Tramba, Gujarat, India',
    longitude: 70.9093529,
    latitude: 22.2267533,
  },
  {
    name: 'Dhandhalpur',
    place_id: 'ChIJKcpP_pAEWTkR2DDAvwLDhOI',
    address_components: [
      'Dhandhalpur',
      'Surendranagar',
      'Gujarat',
      'India',
      '363440',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Dhandhalpur',
    },
    description: 'Dhandhalpur, Gujarat, India',
    longitude: 71.35274729999999,
    latitude: 22.3866556,
  },
  {
    name: 'Bhutkotda',
    place_id: 'ChIJfdzjznHqWTkR8qbcTf8IQ2o',
    address_components: ['Bhutkotda', 'Rajkot', 'Gujarat', 'India', '363650'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bhutkotda',
    },
    description: 'Bhutkotda, Gujarat, India',
    longitude: 70.7555033,
    latitude: 22.5804675,
  },
  {
    name: 'Jafarabad',
    place_id: 'ChIJ9Vet4DtS4jsRWxV25-Hphbc',
    address_components: ['Jafarabad', 'Amreli', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Amreli, Gujarat',
      main_text: 'Jafarabad',
    },
    description: 'Jafarabad, Amreli, Gujarat',
    longitude: 71.3653796,
    latitude: 20.8681767,
  },
  {
    name: 'Padvala',
    place_id: 'ChIJkSrH6iCQVzkR1OmvTnLXw3w',
    address_components: ['Padvala', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Padvala',
    },
    description: 'Padvala, Rajkot, Gujarat',
    longitude: 70.2348797,
    latitude: 21.9303163,
  },
  {
    name: 'Nadiad',
    place_id: 'ChIJVSwkCwZbXjkRCE405YPTFcQ',
    address_components: ['Nadiad', 'Kheda', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Kheda, Gujarat',
      main_text: 'Nadiad',
    },
    description: 'Nadiad, Kheda, Gujarat',
    longitude: 72.86336349999999,
    latitude: 22.6915853,
  },
  {
    name: 'Kamlapur',
    place_id: 'ChIJWSDsrKP4WDkROUv6dKco6n8',
    address_components: ['Kamlapur', 'Rajkot', 'Gujarat', 'India', '363520'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kamlapur',
    },
    description: 'Kamlapur, Gujarat, India',
    longitude: 71.20129159999999,
    latitude: 22.147979,
  },
  {
    name: 'Daman',
    place_id: 'ChIJEUhek3Xa4DsRJrgGQU-1OWM',
    address_components: [
      'Daman',
      'Daman',
      'Dadra and Nagar Haveli and Daman and Diu',
      'India',
    ],
    structured_formatting: {
      secondary_text: 'Daman, Dadra and Nagar Haveli and Daman and Diu',
      main_text: 'Daman',
    },
    description: 'Daman, Daman, Dadra and Nagar Haveli and Daman and Diu',
    longitude: 72.8327991,
    latitude: 20.3973736,
  },
  {
    name: 'Visavadar',
    place_id: 'ChIJ6f0VE6aj4jsR9bhm4Fjnceg',
    address_components: ['Visavadar', 'Junagadh', 'Gujarat', 'India', '362130'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Visavadar',
    },
    description: 'Visavadar, Gujarat, India',
    longitude: 70.7522299,
    latitude: 21.3410369,
  },
  {
    name: 'Sanosara',
    place_id: 'ChIJ6fOdP4ClWDkRggE8cHzKkI4',
    address_components: ['Sanosara', 'Bhavnagar', 'Gujarat', 'India', '364230'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Sanosara',
    },
    description: 'Sanosara, Gujarat, India',
    longitude: 71.7607653,
    latitude: 21.7295924,
  },
  {
    name: 'MUNJKA',
    place_id: 'ChIJueEDpufLWTkRSr-rvxIJpn0',
    address_components: [
      'Munjka',
      'Rajkot',
      'Rajkot',
      'Gujarat',
      'India',
      '360005',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Munjka',
    },
    description: 'Munjka, Gujarat, India',
    longitude: 70.7436094,
    latitude: 22.2930753,
  },
  {
    name: 'DEESA',
    place_id: 'ChIJW_3Rtv28XDkR4wiXlDxkf2Y',
    address_components: ['Deesa', 'Banaskantha', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Banaskantha, Gujarat',
      main_text: 'Deesa',
    },
    description: 'Deesa, Banaskantha, Gujarat',
    longitude: 72.1906739,
    latitude: 24.2585055,
  },
  {
    name: 'BHAVNAGAR',
    place_id: 'ChIJL064q4FQXzkRbHETbkzWdvY',
    address_components: ['Bhavnagar', 'Bhavnagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Bhavnagar, Gujarat',
      main_text: 'Bhavnagar',
    },
    description: 'Bhavnagar, Bhavnagar, Gujarat',
    longitude: 72.15193040000001,
    latitude: 21.7644725,
  },
  {
    name: 'DHOLKA',
    place_id: 'ChIJdxgcVonsXjkRMX0cfnIkhm0',
    address_components: ['Dholka', 'Ahmedabad', 'Gujarat', 'India', '382225'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Dholka',
    },
    description: 'Dholka, Gujarat, India',
    longitude: 72.4402368,
    latitude: 22.7349352,
  },
  {
    name: 'VIJAPUR',
    place_id: 'ChIJqRY9L261XTkRKXPbsSJQD0g',
    address_components: ['Vijapur', 'Mehsana', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Mehsana, Gujarat',
      main_text: 'Vijapur',
    },
    description: 'Vijapur, Mehsana, Gujarat',
    longitude: 72.7510921,
    latitude: 23.5609405,
  },
  {
    name: 'RAMOL',
    place_id: 'ChIJCTXmBIKIXjkR0bgKOZ_awFg',
    address_components: [
      'Ramol',
      'Ahmedabad',
      'Ahmedabad',
      'Gujarat',
      'India',
      '382449',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Ramol',
    },
    description: 'Ramol, Gujarat, India',
    longitude: 72.6558824,
    latitude: 22.9800485,
  },
  {
    name: 'RANOLI',
    place_id: 'ChIJAydLbXqrXzkR8ZGIfX6GMyY',
    address_components: ['Ranoli', 'Anand', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Anand, Gujarat',
      main_text: 'Ranoli',
    },
    description: 'Ranoli, Anand, Gujarat',
    longitude: 72.8072342,
    latitude: 22.3826508,
  },
  {
    name: 'PARAPIPALIYA',
    place_id: 'ChIJRX9bv-nIWTkRjFELE-toc7c',
    address_components: [
      'Para Pipaliya',
      'Rajkot',
      'Gujarat',
      'India',
      '360006',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Parapipaliya',
    },
    description: 'Para Pipaliya, Gujarat, India',
    longitude: 70.7421226,
    latitude: 22.357227,
  },
  {
    name: 'BALSAR',
    place_id: 'ChIJ8RZ_ac3MWTkRtNG2LbQ0ovE',
    address_components: ['Balsar', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Balsar',
    },
    description: 'Balsar, Rajkot, Gujarat',
    longitude: 70.6841352,
    latitude: 22.2000132,
  },
  {
    name: 'TARSALI',
    place_id: 'ChIJ19kieprzXzkRDATuzpdv9sI',
    address_components: ['Tarsali', 'Bharuch', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Bharuch, Gujarat',
      main_text: 'Tarsali',
    },
    description: 'Tarsali, Bharuch, Gujarat',
    longitude: 73.1420072,
    latitude: 21.8508999,
  },
  {
    name: 'BOPAL',
    place_id: 'ChIJ337uypibXjkRlkRQ7keEY00',
    address_components: [
      'Bopal',
      'Ahmedabad',
      'Ahmedabad',
      'Gujarat',
      'India',
      '380058',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bopal',
    },
    description: 'Bopal, Gujarat, India',
    longitude: 72.4634117,
    latitude: 23.0336769,
  },
  {
    name: 'UMARALA',
    place_id: 'ChIJ2alqVeGwWDkRuuw2ZoUvD6Q',
    address_components: ['Umrala', 'Bhavnagar', 'Gujarat', 'India', '364330'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Umarala',
    },
    description: 'Umrala, Gujarat, India',
    longitude: 71.80524640000002,
    latitude: 21.8437759,
  },
  {
    name: 'KANSUMARA',
    place_id: 'ChIJPbrwbNwUVzkRj0B-yw8Hj8Y',
    address_components: [
      'Kansumara',
      'Jamnagar',
      'Jamnagar',
      'Gujarat',
      'India',
      '361006',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kansumara',
    },
    description: 'Kansumara, Gujarat, India',
    longitude: 70.0317057,
    latitude: 22.4272107,
  },
  {
    name: 'DOLVAN',
    place_id: 'ChIJj_JJ5DeE4DsRfR-Ma7ogVJQ',
    address_components: ['Dolvan', 'Tapi', 'Gujarat', 'India', '394635'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Dolvan',
    },
    description: 'Dolvan, Gujarat, India',
    longitude: 73.3219712,
    latitude: 20.9056025,
  },
  {
    name: 'MAKHIYALA',
    place_id: 'ChIJzTP6kbQCWDkRG3NXB8HJDk4',
    address_components: ['Makhiyala', 'Junagadh', 'Gujarat', 'India', '362037'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Makhiyala',
    },
    description: 'Makhiyala, Gujarat, India',
    longitude: 70.4506293,
    latitude: 21.6186369,
  },
  {
    name: 'KHERALU',
    place_id: 'ChIJGz3SM-NVXDkRCMk3DvG4aqk',
    address_components: ['Kheralu', 'Mehsana', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Mehsana, Gujarat',
      main_text: 'Kheralu',
    },
    description: 'Kheralu, Mehsana, Gujarat',
    longitude: 72.6189503,
    latitude: 23.8852929,
  },
  {
    name: 'THARAD',
    place_id: 'ChIJMZkbIQpJWzkRFSeXQpAElRw',
    address_components: ['Tharad', 'Banaskantha', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Banaskantha, Gujarat',
      main_text: 'Tharad',
    },
    description: 'Tharad, Banaskantha, Gujarat',
    longitude: 71.6271514,
    latitude: 24.396687,
  },
  {
    name: 'CHACHAPAR',
    place_id: 'ChIJC80weifuWTkRMdXUD1IGr1I',
    address_components: ['Chachapar', 'Rajkot', 'Gujarat', 'India', '363641'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Chachapar',
    },
    description: 'Chachapar, Gujarat, India',
    longitude: 70.6848787,
    latitude: 22.7453436,
  },
  {
    name: 'KESHOD',
    place_id: 'ChIJZe2tTqJQ_TsRuLRl_VRj7B4',
    address_components: ['Keshod', 'Junagadh', 'Gujarat', 'India', '362220'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Keshod',
    },
    description: 'Keshod, Gujarat, India',
    longitude: 70.2492882,
    latitude: 21.2997164,
  },
  {
    name: 'MOTIKHAVDI',
    place_id: 'ChIJKR52a1wXVzkRLtnuEPI6dbU',
    address_components: ['Motikhavdi', 'Jamnagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Jamnagar, Gujarat',
      main_text: 'Motikhavdi',
    },
    description: 'Motikhavdi, Jamnagar, Gujarat',
    longitude: 69.84495059999999,
    latitude: 22.3550732,
  },
  {
    name: 'HALVAD',
    place_id: 'ChIJ8xthULgqWjkRN6Nv8Cvr6U4',
    address_components: ['Halvad', 'Morbi', 'Gujarat', 'India', '363330'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Halvad',
    },
    description: 'Halvad, Gujarat, India',
    longitude: 71.1823868,
    latitude: 23.013705,
  },
  {
    name: 'AMBAJI',
    place_id: 'ChIJ_-JnRfciXTkRQxv2q73ibro',
    address_components: ['Ambaji', 'Banaskantha', 'Gujarat', 'India', '385110'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Ambaji',
    },
    description: 'Ambaji, Gujarat, India',
    longitude: 72.8516531,
    latitude: 24.3310019,
  },
  {
    name: 'RAMNAGAR',
    place_id: 'ChIJLakwyp0TCjkRWQiCHKcRrWE',
    address_components: [
      'Ramnagar',
      'Nainital',
      'Uttarakhand',
      'India',
      '244715',
    ],
    structured_formatting: {
      secondary_text: 'Uttarakhand, India',
      main_text: 'Ramnagar',
    },
    description: 'Ramnagar, Uttarakhand, India',
    longitude: 79.1264997,
    latitude: 29.3947643,
  },
  {
    name: 'TALAJA',
    place_id: 'ChIJm8003qX24TsRCyhVsGLmgNk',
    address_components: ['Talaja', 'Bhavnagar', 'Gujarat', 'India', '364140'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Talaja',
    },
    description: 'Talaja, Gujarat, India',
    longitude: 72.0327247,
    latitude: 21.3514348,
  },
  {
    name: 'ZANKHVAV',
    place_id: 'ChIJD7IDp7MN4DsRXAIV67YL4NU',
    address_components: ['Zankhvav', 'Surat', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Surat, Gujarat',
      main_text: 'Zankhvav',
    },
    description: 'Zankhvav, Surat, Gujarat',
    longitude: 73.32075999999999,
    latitude: 21.4495504,
  },
  {
    name: 'HADAMTALA',
    place_id: 'ChIJo317N1AwWDkRTaGCungoavE',
    address_components: ['Hadamtala', 'Rajkot', 'Gujarat', 'India', '360070'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Hadamtala',
    },
    description: 'Hadamtala, Gujarat, India',
    longitude: 70.65885639999999,
    latitude: 22.0468483,
  },
  {
    name: ' VIDHYANAGAR',
    place_id: 'ChIJJ9rNMXROXjkR-oc3Z2cjnak',
    address_components: [
      'Vallabh Vidyanagar',
      'Anand',
      'Anand',
      'Gujarat',
      'India',
    ],
    structured_formatting: {
      secondary_text: 'Anand, Gujarat',
      main_text: ' Vidhyanagar',
    },
    description: 'Vallabh Vidyanagar, Anand, Gujarat',
    longitude: 72.92939439999999,
    latitude: 22.5459097,
  },
  {
    name: 'BARDOLI',
    place_id: 'ChIJGSMGYmln4DsRs2oXHqhdpkI',
    address_components: ['Bardoli', 'Surat', 'Gujarat', 'India', '394601'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bardoli',
    },
    description: 'Bardoli, Gujarat, India',
    longitude: 73.1122499,
    latitude: 21.1255374,
  },
  {
    name: 'BANGAVDI',
    place_id: 'ChIJRXM2yx_mWTkRpVn-q36-YOY',
    address_components: ['Bangavadi', 'Rajkot', 'Gujarat', 'India', '363650'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bangavdi',
    },
    description: 'Bangavadi, Gujarat, India',
    longitude: 70.6157308,
    latitude: 22.6288249,
  },
  {
    name: 'CHOTILA',
    place_id: 'ChIJ_Zz-PhyoWTkRRpZ1MrZpPIA',
    address_components: [
      'Chotila',
      'Surendranagar',
      'Gujarat',
      'India',
      '363520',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Chotila',
    },
    description: 'Chotila, Gujarat, India',
    longitude: 71.19621,
    latitude: 22.424833,
  },
  {
    name: 'CHITRASANI',
    place_id: 'ChIJnymZn43CXDkRlM908ctan_4',
    address_components: [
      'Chitrasani',
      'Banaskantha',
      'Gujarat',
      'India',
      '385010',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Chitrasani',
    },
    description: 'Chitrasani, Gujarat, India',
    longitude: 72.483507,
    latitude: 24.26778,
  },
  {
    name: 'RAPAR',
    place_id: 'ChIJ_Uu9lVxjWjkRkQ7tbfKRH-U',
    address_components: ['Rapar', 'Kutch', 'Gujarat', 'India', '370165'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Rapar',
    },
    description: 'Rapar, Gujarat, India',
    longitude: 70.6447369,
    latitude: 23.5729757,
  },
  {
    name: 'BHADIYAD',
    place_id: 'ChIJaRZ7vnQmXzkRXt5w7J7AzP8',
    address_components: ['Bhadiyad', 'Ahmedabad', 'Gujarat', 'India', '382463'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bhadiyad',
    },
    description: 'Bhadiyad, Gujarat, India',
    longitude: 72.1675288,
    latitude: 22.2807437,
  },
  {
    name: 'NIKAVA',
    place_id: 'ChIJ7bWL8FnTWTkReY6tr9Du__I',
    address_components: ['Nikava', 'Jamnagar', 'Gujarat', 'India', '361162'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Nikava',
    },
    description: 'Nikava, Gujarat, India',
    longitude: 70.5316993,
    latitude: 22.1905327,
  },
  {
    name: 'SEVALIYA',
    place_id: 'ChIJqZAq0LkjXjkRA_nqMVZQwVU',
    address_components: ['Sevaliya', 'Kheda', 'Gujarat', 'India', '388245'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Sevaliya',
    },
    description: 'Sevaliya, Gujarat, India',
    longitude: 73.3443425,
    latitude: 22.8100749,
  },
  {
    name: 'NANAFOFALIA',
    place_id: 'ChIJw1sTM5bpXzkRU2_s8kE-MP0',
    address_components: ['Vadodara', 'Vadodara', 'Gujarat', 'India', '391210'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Nanafofalia',
    },
    description: 'Vadodara, Gujarat, India',
    longitude: 73.20474949999999,
    latitude: 22.084766,
  },
  {
    name: 'SUTARPADA',
    place_id: 'ChIJM43fVPgt5zsR80ubzHkFpQw',
    address_components: [
      'Sutarpada',
      'Thane',
      'Maharashtra',
      'India',
      '401606',
    ],
    structured_formatting: {
      secondary_text: 'Maharashtra, India',
      main_text: 'Sutarpada',
    },
    description: 'Sutarpada, Maharashtra, India',
    longitude: 72.8973302,
    latitude: 20.1531556,
  },
  {
    name: 'VAVDI',
    place_id: 'ChIJT0IrPJbKWTkRy_u1VQRBMMk',
    address_components: [
      'Vavdi',
      'Rajkot',
      'Rajkot',
      'Gujarat',
      'India',
      '360004',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Vavdi',
    },
    description: 'Vavdi, Gujarat, India',
    longitude: 70.7952438,
    latitude: 22.2328699,
  },
  {
    name: 'MATA NO MADH',
    place_id: 'ChIJ2wqAbR-HUTkRAD7VzhHivME',
    address_components: ['Mata no Madh', 'Kutch', 'Gujarat', 'India', '370625'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Mata No Madh',
    },
    description: 'Mata no Madh, Gujarat, India',
    longitude: 68.94948839999999,
    latitude: 23.5413751,
  },
  {
    name: 'HARIPAR PAL',
    place_id: 'ChIJlwZMrg_MWTkRwALe2WhytXg',
    address_components: ['Haripar Pal', 'Rajkot', 'Gujarat', 'India', '360005'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Haripar Pal',
    },
    description: 'Haripar Pal, Gujarat, India',
    longitude: 70.7064389,
    latitude: 22.2785072,
  },
  {
    name: 'PRANTIJ',
    place_id: 'ChIJ3UGrux_PXTkR-cp0i9jIPtM',
    address_components: ['Prantij', 'Sabarkatha', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Sabarkatha, Gujarat',
      main_text: 'Prantij',
    },
    description: 'Prantij, Sabarkatha, Gujarat',
    longitude: 72.8528118,
    latitude: 23.4367496,
  },
  {
    name: 'MANJUSAR',
    place_id: 'ChIJlfXNy4jMXzkRQzSv8Hz1BT0',
    address_components: ['Manjusar', 'Vadodara', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Vadodara, Gujarat',
      main_text: 'Manjusar',
    },
    description: 'Manjusar, Vadodara, Gujarat',
    longitude: 73.1998604,
    latitude: 22.4451544,
  },
  {
    name: 'KOTARVADA',
    place_id: 'ChIJPR547atGWzkRVzoKKdnM2HU',
    address_components: ['Kotarwada', 'Banaskantha', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Banaskantha, Gujarat',
      main_text: 'Kotarvada',
    },
    description: 'Kotarwada, Banaskantha, Gujarat',
    longitude: 71.66140229999999,
    latitude: 24.2470448,
  },
  {
    name: 'DEVGAM',
    place_id: 'ChIJLy6tRUBkWDkROWIJa9EXn24',
    address_components: ['Devgam', 'Amreli', 'Gujarat', 'India', '365460'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Devgam',
    },
    description: 'Devgam, Gujarat, India',
    longitude: 71.0690907,
    latitude: 21.7613933,
  },
  {
    name: 'PALITANA',
    place_id: 'ChIJn3fSDZQG4jsRYdh1RdLddM4',
    address_components: ['Palitana', 'Bhavnagar', 'Gujarat', 'India', '364270'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Palitana',
    },
    description: 'Palitana, Gujarat, India',
    longitude: 71.82748459999999,
    latitude: 21.5346305,
  },
  {
    name: 'MANEKVADA',
    place_id: 'ChIJHanUx8Gf4jsRxaj6t1Ah5xs',
    address_components: ['Manekwada', 'Junagadh', 'Gujarat', 'India', '365440'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Manekvada',
    },
    description: 'Manekwada, Gujarat, India',
    longitude: 70.84618429999999,
    latitude: 21.4717512,
  },
  {
    name: 'JETPUR',
    place_id: 'ChIJT7j3rGkXWDkRdXifhCdqT9E',
    address_components: ['Jetpur', 'Rajkot', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Rajkot, Gujarat',
      main_text: 'Jetpur',
    },
    description: 'Jetpur, Rajkot, Gujarat',
    longitude: 70.6179777,
    latitude: 21.7546665,
  },
  {
    name: 'RANDHEJA',
    place_id: 'ChIJCdcwMEgsXDkRQ62YbkLCk60',
    address_components: ['Randheja', 'Gandhinagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Gandhinagar, Gujarat',
      main_text: 'Randheja',
    },
    description: 'Randheja, Gandhinagar, Gujarat',
    longitude: 72.64172649999999,
    latitude: 23.292206,
  },
  {
    name: 'BAKROL',
    place_id: 'ChIJPTe4wSJOXjkR2G2tNn8PbwQ',
    address_components: ['Bakrol', 'Anand', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Anand, Gujarat',
      main_text: 'Bakrol',
    },
    description: 'Bakrol, Anand, Gujarat',
    longitude: 72.9112439,
    latitude: 22.5638508,
  },
  {
    name: 'ADESAR',
    place_id: 'ChIJWfW29YtaWjkRTscUeJc2EqY',
    address_components: ['Adesar', 'Kutch', 'Gujarat', 'India', '370155'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Adesar',
    },
    description: 'Adesar, Gujarat, India',
    longitude: 70.9814281,
    latitude: 23.5580562,
  },
  {
    name: 'NANA UMAVDA',
    place_id: 'ChIJ7dKXqtaiWDkRueQj8FjBiZQ',
    address_components: [
      'Nana Umarda',
      'Bhavnagar',
      'Gujarat',
      'India',
      '364740',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Nana Umavda',
    },
    description: 'Nana Umarda, Gujarat, India',
    longitude: 71.6139348,
    latitude: 21.7631098,
  },
  {
    name: 'THALTEJ',
    place_id: 'ChIJByErQKGcXjkRy0vLdNPPt8Y',
    address_components: [
      'Thaltej',
      'Ahmedabad',
      'Ahmedabad',
      'Gujarat',
      'India',
    ],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Thaltej',
    },
    description: 'Thaltej, Ahmedabad, Gujarat',
    longitude: 72.49908909999999,
    latitude: 23.0504131,
  },
  {
    name: 'BAMANGAM',
    place_id: 'ChIJB8tlwVy3XzkRWOQ482WIvAc',
    address_components: ['Bamangam', 'Anand', 'Gujarat', 'India', '388520'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Bamangam',
    },
    description: 'Bamangam, Gujarat, India',
    longitude: 73.00658159999999,
    latitude: 22.2873625,
  },
  {
    name: 'DHASA',
    place_id: 'ChIJmeclMu68WDkRWbcvB4lbRu0',
    address_components: ['Dhasa', 'Amreli', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Amreli, Gujarat',
      main_text: 'Dhasa',
    },
    description: 'Dhasa, Amreli, Gujarat',
    longitude: 71.51480520000001,
    latitude: 21.7837227,
  },
  {
    name: 'VITTHALPUR',
    place_id: 'ChIJKeNQpqsOXDkRd8TOLPPGXDc',
    address_components: ['Vitthalapur', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Vitthalpur',
    },
    description: 'Vitthalapur, Ahmedabad, Gujarat',
    longitude: 72.05422349999999,
    latitude: 23.363723,
  },
  {
    name: 'SOMNATH',
    place_id: 'ChIJdcsXBJ8y_TsRY3mF6Q1RWi8',
    address_components: [
      'Somnath Mandir Road',
      'Veraval',
      'Gir Somnath',
      'Gujarat',
      'India',
      '362268',
    ],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Somnath',
    },
    description: 'Somnath Mandir Road, Gujarat, India',
    longitude: 70.4011569,
    latitude: 20.8880469,
  },
  {
    name: 'GADHADA',
    place_id: 'ChIJD9rdsSXAWDkRmYHFjtTpaSg',
    address_components: ['Gadhada', 'Bhavnagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Bhavnagar, Gujarat',
      main_text: 'Gadhada',
    },
    description: 'Gadhada, Bhavnagar, Gujarat',
    longitude: 71.57536259999999,
    latitude: 21.9681716,
  },
  {
    name: 'GHOGHA',
    place_id: 'ChIJkas28gRfXzkRsY_sLtasz9w',
    address_components: ['Ghogha', 'Bhavnagar', 'Gujarat', 'India', '364110'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Ghogha',
    },
    description: 'Ghogha, Gujarat, India',
    longitude: 72.27486859999999,
    latitude: 21.6848795,
  },
  {
    name: 'KHENGARKA',
    place_id: 'ChIJyUPYkvfYWTkRAEqK907-i_8',
    address_components: ['Khengarka', 'Rajkot', 'Gujarat', 'India', '361210'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Khengarka',
    },
    description: 'Khengarka, Gujarat, India',
    longitude: 70.47294339999999,
    latitude: 22.4053059,
  },
  {
    name: 'DHROL',
    place_id: 'ChIJs-6dKJ9fVzkRC8FSUdxPTDw',
    address_components: ['Dhrol', 'Jamnagar', 'Gujarat', 'India', '361210'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Dhrol',
    },
    description: 'Dhrol, Gujarat, India',
    longitude: 70.4223635,
    latitude: 22.5617178,
  },
  {
    name: 'MOVAN',
    place_id: 'ChIJqfrq7d75VjkRIQpKWxx-9E4',
    address_components: ['Movan', 'Jamnagar', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Jamnagar, Gujarat',
      main_text: 'Movan',
    },
    description: 'Movan, Jamnagar, Gujarat',
    longitude: 69.4844129,
    latitude: 22.1194377,
  },
  {
    name: 'OKHA',
    place_id: 'ChIJE0_8OjcYzF4R4dYMHY6WYvg',
    address_components: ['Okha', 'Okhinskii', 'Sakhalin Oblast', 'Russia'],
    structured_formatting: {
      secondary_text: 'Okhinskii, Sakhalin Oblast',
      main_text: 'Okha',
    },
    description: 'Okha, Okhinskii, Sakhalin Oblast',
    longitude: 142.9521874,
    latitude: 53.5893264,
  },
  {
    name: 'VIRVA',
    place_id: 'ChIJX-B-mQHFyIARxkJvHMEXgeM',
    address_components: [
      '4505',
      'South Maryland Parkway',
      'University District',
      'Las Vegas',
      'Clark County',
      'Nevada',
      'United States',
      '89154',
    ],
    structured_formatting: {
      secondary_text: 'Nevada, United States',
      main_text: 'Virva',
    },
    description: '4505, Nevada, United States',
    longitude: -115.1425003,
    latitude: 36.1072396,
  },
  {
    name: 'CHANGODER',
    place_id: 'ChIJdfO_5tqQXjkRcCzm2_Ly1i8',
    address_components: ['Changodar', 'Ahmedabad', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Ahmedabad, Gujarat',
      main_text: 'Changoder',
    },
    description: 'Changodar, Ahmedabad, Gujarat',
    longitude: 72.43441539999999,
    latitude: 22.9147264,
  },
  {
    name: 'TRAMBHA',
    place_id: 'ChIJF0B5qAAAK4cRv6cPOdMYAV0',
    address_components: [
      'suite 3-5',
      '955',
      'West Chandler Heights Road',
      'Chandler',
      'Maricopa County',
      'Arizona',
      'United States',
      '85248',
      '5729',
    ],
    structured_formatting: {
      secondary_text: 'United States, 85248',
      main_text: 'Trambha',
    },
    description: 'suite 3-5, United States, 85248',
    longitude: -111.856999,
    latitude: 33.23244,
  },
  {
    name: 'CHATRAL',
    place_id: 'ChIJPR5tiro32TgRIrIc_TEsu4o',
    address_components: [
      'Chatral',
      'Charsadda',
      'Charsadda',
      'Khyber Pakhtunkhwa',
      'Pakistan',
    ],
    structured_formatting: {
      secondary_text: 'Charsadda, Khyber Pakhtunkhwa',
      main_text: 'Chatral',
    },
    description: 'Chatral, Charsadda, Khyber Pakhtunkhwa',
    longitude: 71.7967213,
    latitude: 34.1561183,
  },
  {
    name: 'DIU',
    place_id: 'ChIJcx_A5Lxw44kRlEmkrOy7bm0',
    address_components: [
      '1000',
      '1',
      'Charles Park',
      'East Cambridge',
      'Cambridge',
      'Middlesex County',
      'Massachusetts',
      'United States',
      '02141',
    ],
    structured_formatting: {
      secondary_text: 'Massachusetts, United States',
      main_text: 'Diu',
    },
    description: '1000, Massachusetts, United States',
    longitude: -71.07672,
    latitude: 42.366754,
  },
  {
    name: 'DEVDA',
    place_id: 'ChIJJx7QmUnUTYYRE71l5h9WFG4',
    address_components: [
      '#280',
      '1205',
      'South White Chapel Boulevard',
      'Southlake',
      'Tarrant County',
      'Texas',
      'United States',
      '76092',
    ],
    structured_formatting: {
      secondary_text: 'Texas, United States',
      main_text: 'Devda',
    },
    description: '#280, Texas, United States',
    longitude: -97.1554166,
    latitude: 32.9260097,
  },
  {
    name: 'NIKOL',
    place_id: 'ChIJr3kyHfsI3IARp2sVjrLON98',
    address_components: [
      '#100',
      '1953',
      'San Elijo Avenue',
      'Cardiff',
      'Encinitas',
      'San Diego County',
      'California',
      'United States',
      '92007',
    ],
    structured_formatting: {
      secondary_text: 'California, United States',
      main_text: 'Nikol',
    },
    description: '#100, California, United States',
    longitude: -117.2833639,
    latitude: 33.0232005,
  },
  {
    name: 'NAROL',
    place_id: 'ChIJt3P8lpKsJEcRgcH4pPSLF98',
    address_components: [
      'Narol',
      'Lubaczów County',
      'Podkarpackie Voivodeship',
      'Poland',
      '37',
    ],
    structured_formatting: {
      secondary_text: 'Podkarpackie Voivodeship, Poland',
      main_text: 'Narol',
    },
    description: 'Narol, Podkarpackie Voivodeship, Poland',
    longitude: 23.3268124,
    latitude: 50.3490504,
  },
  {
    name: 'UMRA',
    place_id: 'ChIJuf9-H_BQ2YARJ-lLOnmVcXk',
    address_components: [
      '8318',
      'Jamacha Road',
      'Spring Valley',
      'San Diego County',
      'California',
      'United States',
      '91977',
      '3764',
    ],
    structured_formatting: {
      secondary_text: 'United States, 91977',
      main_text: 'Umra',
    },
    description: '8318, United States, 91977',
    longitude: -117.0191,
    latitude: 32.71623599999999,
  },
  {
    name: 'MALIA',
    place_id: 'ChIJQ3Yxi8VkmhQRfsDV39iWTLk',
    address_components: ['Malia, Crete', 'Heraklion', 'Greece', '700 07'],
    structured_formatting: {
      secondary_text: 'Heraklion, Greece',
      main_text: 'Malia',
    },
    description: 'Malia, Crete, Heraklion, Greece',
    longitude: 25.4628694,
    latitude: 35.2831684,
  },
  {
    name: 'SHAPUR',
    place_id: 'ChIJc4AOMImAhYARx_rcrFhkYuI',
    address_components: [
      '155',
      'Post Street',
      'Financial District',
      'San Francisco',
      'San Francisco County',
      'California',
      'United States',
      '94108',
    ],
    structured_formatting: {
      secondary_text: 'California, United States',
      main_text: 'Shapur',
    },
    description: '155, California, United States',
    longitude: -122.4045489,
    latitude: 37.7886637,
  },
  {
    name: 'BOUNDRY',
    place_id: 'ChIJM1GNPFP9yIcRY8tF8RZDQY0',
    address_components: [
      'Boundry Hollow',
      'White Rock Township',
      'McDonald County',
      'Missouri',
      'United States',
      '64856',
    ],
    structured_formatting: {
      secondary_text: 'Missouri, United States',
      main_text: 'Boundry',
    },
    description: 'Boundry Hollow, Missouri, United States',
    longitude: -94.2343751,
    latitude: 36.5417407,
  },
  {
    name: 'KUNDARIYA',
    place_id: 'ChIJkQJdfySmzokRaYLkVpuOPq0',
    address_components: [
      'State College',
      'Centre County',
      'Pennsylvania',
      'United States',
      '16801',
    ],
    structured_formatting: {
      secondary_text: 'Pennsylvania, United States',
      main_text: 'Kundariya',
    },
    description: 'State College, Pennsylvania, United States',
    longitude: -77.8599084,
    latitude: 40.7982133,
  },
  {
    name: 'MAHIJADA',
    place_id: 'ChIJzfSIDXWNXjkRbC32CgOqhXE',
    address_components: ['Mahijda', 'Ahmedabad', 'Gujarat', 'India', '382425'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Mahijada',
    },
    description: 'Mahijda, Gujarat, India',
    longitude: 72.5426657,
    latitude: 22.8274309,
  },
  {
    name: 'DHOLKIYA',
    place_id: 'ChIJjVH9u2bEQIYRa8vPLFMcJEY',
    address_components: [
      'Suite 200',
      '9090',
      'Katy Freeway',
      'Northwest Houston',
      'Houston',
      'Harris County',
      'Texas',
      'United States',
      '77024',
    ],
    structured_formatting: {
      secondary_text: 'Texas, United States',
      main_text: 'Dholkiya',
    },
    description: 'Suite 200, Texas, United States',
    longitude: -95.5131561,
    latitude: 29.7855515,
  },
  {
    name: 'MIRULI',
    place_id: 'ChIJrfMYEvD90YUR6KZyM4VNsQQ',
    address_components: [
      'Lucero',
      'Santa María del Monte',
      'Ciudad de México',
      'Ciudad de México',
      'Mexico',
      '09850',
    ],
    structured_formatting: {
      secondary_text: 'Ciudad de México, Mexico',
      main_text: 'Miruli',
    },
    description: 'Lucero, Ciudad de México, Mexico',
    longitude: -99.0895156,
    latitude: 19.3519763,
  },
  {
    name: 'MAJNUSAR',
    place_id: 'ChIJlfXNy4jMXzkRQzSv8Hz1BT0',
    address_components: ['Manjusar', 'Vadodara', 'Gujarat', 'India'],
    structured_formatting: {
      secondary_text: 'Vadodara, Gujarat',
      main_text: 'Majnusar',
    },
    description: 'Manjusar, Vadodara, Gujarat',
    longitude: 73.1998604,
    latitude: 22.4451544,
  },
  {
    name: 'KIM',
    place_id: 'ChIJmcFJVcZ_t4cRsUruoBZm7WA',
    address_components: [
      '3521',
      'Legionville Ln',
      'Independence',
      'Fawn Creek Township',
      'Montgomery County',
      'Kansas',
      'United States',
      '67301',
      '7156',
    ],
    structured_formatting: {
      secondary_text: 'United States, 67301',
      main_text: 'Kim',
    },
    description: '3521, United States, 67301',
    longitude: -95.7436683,
    latitude: 37.0852884,
  },
  {
    name: 'SAYLA',
    place_id: 'ChIJoWnNnOtXDogRo8Sx7kPqrls',
    address_components: [
      '309',
      '120',
      'Spalding Drive',
      'Naperville Park District',
      'Naperville',
      'Naperville Township',
      'DuPage County',
      'Illinois',
      'United States',
      '60540',
    ],
    structured_formatting: {
      secondary_text: 'Illinois, United States',
      main_text: 'Sayla',
    },
    description: '309, Illinois, United States',
    longitude: -88.1521214,
    latitude: 41.7610005,
  },
  {
    name: 'BEDI',
    place_id: 'ChIJlXqroljT54gRiAzw2eLkP0Y',
    address_components: [
      '2654',
      'Southwest 32nd Place',
      'Ocala',
      'Marion County',
      'Florida',
      'United States',
      '34471',
    ],
    structured_formatting: {
      secondary_text: 'Florida, United States',
      main_text: 'Bedi',
    },
    description: '2654, Florida, United States',
    longitude: -82.1665953,
    latitude: 29.1556295,
  },
  {
    name: 'UNA',
    place_id: 'ChIJm2CAdUPowIcRLPRALH9FsoE',
    address_components: [
      'Suite 312',
      '400',
      'East Red Bridge Road',
      'Red Bridge North',
      'Kansas City',
      'Kaw Township',
      'Jackson County',
      'Missouri',
      'United States',
      '64131',
    ],
    structured_formatting: {
      secondary_text: 'Missouri, United States',
      main_text: 'Una',
    },
    description: 'Suite 312, Missouri, United States',
    longitude: -94.5870297,
    latitude: 38.9263954,
  },
  {
    name: 'KALAWAD',
    place_id: 'ChIJw22_nP1-VzkRm626A4LIaSc',
    address_components: ['Kalavad', 'Jamnagar', 'Gujarat', 'India', '361160'],
    structured_formatting: {
      secondary_text: 'Gujarat, India',
      main_text: 'Kalawad',
    },
    description: 'Kalavad, Gujarat, India',
    longitude: 70.38070580000002,
    latitude: 22.2081932,
  },
  {
    name: 'PADANA',
    place_id: 'ChIJj7scmzs3eUcRqoxleo6Tvgc',
    address_components: [
      '41',
      'Via Olimpia',
      'Paese',
      'Paese',
      'Provincia di Treviso',
      'Veneto',
      'Italy',
      '31038',
    ],
    structured_formatting: {
      secondary_text: 'Veneto, Italy',
      main_text: 'Padana',
    },
    description: '41, Veneto, Italy',
    longitude: 12.168517,
    latitude: 45.6843721,
  },
  {
    name: 'NAGHEDI',
    place_id: 'ChIJoesLAzEzK4gRJkQ5uWaZFEY',
    address_components: [
      '622',
      'Mount Pleasant Road',
      'Old Toronto',
      'Toronto',
      'Toronto Division',
      'Ontario',
      'Canada',
      'M4S 2M8',
    ],
    structured_formatting: {
      secondary_text: 'Ontario, Canada',
      main_text: 'Naghedi',
    },
    description: '622, Ontario, Canada',
    longitude: -79.38865349999999,
    latitude: 43.70411259999999,
  },
];